### ISSUE TITLE
게시글 리스트 뷰 수정 및 메인 컬러 변경

### ISSUE THREAD

**Issue by 1jeongg** [ApptiveDev/apptive-17th-fruitable-frontend#13]
## TODO
- [x] 게시글 스크롤 위치 설정하기
- [x] 사용자 프로필 내용 수정하기 
- [x] 과일, 채소 구분 버튼 -> 탭바로 변경
- [x] 메인 컬러 변경

## 스크린샷 
<img width="552" alt="스크린샷 2022-11-10 오후 4 39 52" src="https://user-images.githubusercontent.com/84652886/201556239-429900da-8c53-4609-8552-54ef3db60e4c.png">
